name: Publish-Packages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: actions/setup-node@v2
        name: Setup NodeJS v16
        with:
          node-version: '16'

      - name: Publish modules
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
          npm publish --workspaces
          rm -rf .npmrc

      - name: Bump version
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions"
          npm version patch --workspaces --include-workspace-root --git-tag-version=false --commit-hooks=false
          git add .
          git commit -m "[CI] bump patch version"
          git push origin master
