name: Publish-Packages
concurrency: deploy_packages # queue one deploy at a time

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
        with:
          token: ${{ secrets.EHS_SERVICE_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        name: Setup NodeJS v16
        with:
          node-version: '16'

      - name: Bump version
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          # There is no clean solution to allow push access to github actions when protected branches are enabled.
          # The workaround is to use a separate github "bot" account and its PAT.
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
          git config --global user.email "bot@ehs-service.org"
          git config --global user.name "ehs-service-bot"
          lerna publish patch --yes
